export enum MusicPlayerActionType {
  MEDIA_PLAY,
  MEDIA_PAUSE,
  MEDIA_TOGGLE_REPEAT,
  MEDIA_NEXT,
  MEDIA_BACK,
  MEDIA_TIME_CHANGE,
  VOLUME_CHANGE,
  MEDIA_ADD_TRACK,
  UPDATE_TIME_PROGRESSION,
  HANDLE_TRACK_LOADED,
}
