export enum MusicPlayerActionType {
  MEDIA_PLAY,
  MEDIA_PAUSE,
  MEDIA_TOGGLE_REPEAT,
  MEDIA_NEXT,
  MEDIA_BACK,
  MEDIA_SEEK_CHANGE,
  SET_PLAYER,
  VOLUME_CHANGE,
  MEDIA_ADD_TRACK,
  UPDATE_TIME_PROGRESSION,
  MEDIA_SET_DURATION,
}
